import os, pygame, numpy
from time import ctime
from re import compile
from collections import defaultdict, Counter
RESOLUTION = WIDTH, HEIGHT = 512, 448
FPS = 240; FOV = 90; ASPECT_RATIO = WIDTH / HEIGHT
NEAR = 0.01; FAR = 50
TUNADİTOR_VERSİON = "v0.8"
#NOOO THIS IS SOMETHING CODERSPACE WOULD DO
#we don't memic them

VERTEX_SHADER = """
#version 330 core

in vec3 position;
in vec2 texCoords;

out vec2 uvs;

void main()
{
    gl_Position = vec4(position, 1.0);
    uvs = texCoords;
}
"""

FRAGMENT_SHADER = """
#version 330 core

uniform sampler2D tex;

in vec2 uvs;
out vec4 fragColor;

void main()
{
    fragColor = vec4(texture(tex, uvs).rgb, 1.0);
}
"""

def get_uniform_names(program):
  names = set()
  for name in dir(program):
    try: program[name]; names.add(name)
    except KeyError: continue
  return names

def maxint(int, max):
  if int > max: return max
  else: return int

def minint(int, min):
  if int < min: return min
  else: return int

def betweenint(int, min, max, only_for_max=False, only_for_min=False):
  if int: determined_int = 0
  else: determined_int = -1
  while (not ((int >= min or only_for_min) and (int <= max or only_for_max))) and determined_int != int:
    determined_int = int
    if int > max and not only_for_max: int = max - (int - min)
    if int < min and not only_for_min: int = max + (int - min)
  return int

def betweenint_nobacktrack(int, min, max, only_for_max=False, only_for_min=False):
  if int: determined_int = 0
  else: determined_int = -1
  while (not ((int >= min or only_for_min) and (int <= max or only_for_max))) and determined_int != int:
    determined_int = int
    if int > max and not only_for_max: int = min - (int - min)
    if int < min and not only_for_min: int = min + (int - min)
  return int

def snapint(int, snap_to): return round(int / snap_to) * snap_to

def resetint(int, down_to):
  while int > down_to: int -= down_to
  return int

def replace_letter(string, letter_to_replace, replacement_letter):
  new_string = ""
  for char in string:
    if char == letter_to_replace: new_string += replacement_letter
    else: new_string += char
  return new_string

def get_key_from_value(dictionary, value):
  for key, val in dictionary.items():
    if val == value: return key
  return None

def contains_all(a, b):
  ca, cb = Counter(a), Counter(b)
  return all(ca[x] >= cb[x] for x in cb)

def get_material_name(input_string):
  # Common substrings to split on
  substrings = ["terrain", "row", "column", "block"]
  # Find the index of the first occurrence of any of the substrings
  index = min(input_string.find(sub) for sub in substrings if sub in input_string)
  # Extract the material name before the first occurrence of any of the substrings
  material_name = input_string[:index].strip()
  return material_name

def last_access_time(atime):
  return ctime(atime)

def find_files_with_prefix(root_dir, prefix):
  matches = []
  for file in os.listdir(root_dir):
    if prefix in file: matches.append(os.path.join(root_dir, file))
  return matches

def compress_to_rnd_suffix(list_in):
  if list_in:
    grouped_files = defaultdict(list); pattern = compile(r"^(.*)(_rnd\d+\.wav)$"); final_list = []
    for file in list_in:
      match = pattern.match(file)
      if match:base_name = match.group(1); grouped_files[base_name].append(file)
      else: grouped_files[file].append(file)
    for key, group in grouped_files.items():
      if len(group) == 1: final_list.append(group[0])
      else: final_list.append(group)
    return final_list
  else: return []

def compress_to_ind_suffix(list_in):
  if list_in:
    grouped_files = defaultdict(list); pattern = compile(r"^(.*)(_ind\d+\.png)$"); final_list = []
    for file in list_in:
      match = pattern.match(file)
      if match:base_name = match.group(1); grouped_files[base_name].append(file)
      else: grouped_files[file].append(file)
    for key, group in grouped_files.items():
      if len(group) == 1: final_list.append(group[0])
      else: final_list.append(group)
    return final_list
  else: return []

def chop_surface(surface, sub_width, sub_height):
  surface_width, surface_height = surface.get_size()
  chopped_surfaces = []

  for y in range(0, surface_height, sub_height):
    for x in range(0, surface_width, sub_width):
      try:
        sub_surface = surface.subsurface((x, y, sub_width, sub_height)).copy()
        chopped_surfaces.append(sub_surface)
      except: pass

  return chopped_surfaces

def extract_number(filename): return int(''.join(filter(str.isdigit, filename)))

def arabic_numeral(input_string):
  nums = []
  for i_char, char in enumerate(input_string):
    if char.isnumeric():
      if i_char != 0 and input_string[i_char-1].isnumeric(): nums[-1][0] += char
      else: nums.append([char, i_char])
    elif i_char != 0 and input_string[i_char-1].isnumeric(): nums[-1].append(i_char)
            
  for num in nums:
    if len(num) == 3: input_string = input_string[:num[1]]+num[0][::-1]+input_string[num[2]:]
    else: input_string = input_string[:num[1]]+num[0][::-1]
  
  return input_string

battery_mode = {
  "[True, False, False, False, False, False]": "battery level 0",
  "[True, False, False, False, False, True]": "battery level 0 charge",
  "[False, True, False, False, False, False]": "battery level 1",
  "[False, True, False, False, False, True]": "battery level 1 charge",
  "[False, False, True, False, False, False]": "battery level 2",
  "[False, False, True, False, False, True]": "battery level 2 charge",
  "[False, False, False, True, False, False]": "battery level 3",
  "[False, False, False, True, False, True]": "battery level 3 charge",
  "[False, False, False, False, True, False]": "battery full",
  "[False, False, False, False, True, True]": "battery full charge",
  }

def commercial_time(hour):
  if hour >= 12: hour -= 12
  return hour

room_pages = {
  1: "Borders and Gravity",
  2: "UI Settings",
  3: "Room Modes",
}

glyph_pages = {
  1: "Latin",
  2: "Markers and Symbols",
  3: "Latin Accents 1",
  4: "Latin Accents 2",
  5: "Greek",
  6: "Cyrillic",
  7: "Arabic",
  8: "Arabic Accents",
  9: "Quranic Symbols",
  10: "Phonetic",
  11: "Japanese Hiragana",
  12: "Japanese Katakana",
  13: "Japanese Dakuten and Handakuten",
  14: "Japanese Kanji 1",
  15: "Japanese Kanji 2",
  16: "Japanese Kanji 3",
  17: "Japanese Kanji 4",
  18: "Japanese Kanji 5",
  19: "Japanese Kanji 6",
}

basic_colors = {
  "Black": (0, 0, 0),
  "Charcoal": (50, 50, 50),
  "İron": (100, 100, 100),
  "Silver": (200, 200, 200),
  "White": (255, 255, 255),
  "Brown": (128, 64, 0),
  "Red": (255, 0, 0),
  "Patrol": (255, 64, 0),
  "Orange": (255, 128, 0),
  "Yellow": (255, 255, 0),
  "Nano": (128, 255, 0),
  "Green": (0, 255, 0),
  "Turquoise": (0, 255, 196),
  "Cyan": (0, 255, 255),
  "Sea": (0, 128, 255),
  "Blue": (0, 0, 255),
  "İndigo": (128, 0, 255),
  "Magenta": (255, 0, 255),
  "Fuscia": (255, 0, 196),
  "Pink": (255, 128, 196),
  }

colors = {
  "Transparent": "Transparent",
  "Black": (0, 0, 0),
  "Gray Accent 1": (20, 20, 20),
  "Gray Accent 2, Charcoal": (40, 40, 40),
  "Gray Accent 3": (60, 60, 60),
  "Gray Accent 4": (80, 80, 80),
  "Gray Accent 5, İron": (100, 100, 100),
  "Gray Accent 6": (120, 120, 120),
  "Gray Accent 7": (140, 140, 140),
  "Gray Accent 8": (160, 160, 160),
  "Gray Accent 9": (180, 180, 180),
  "Gray Accent 10, Rhino": (200, 200, 200),
  "Gray Accent 11, Silver": (220, 220, 220),
  "Gray Accent 12": (240, 240, 240),
  "White": (255, 255, 255),
  
  "Red": (255, 0, 0),
  "Orange Tint 1, Patrol": (255, 64, 0),
  "Orange Tint 2": (255, 128, 0),
  "Orange Tint 3": (255, 196, 0),
  "Yellow": (255, 255, 0),
  "Yellow Tint 1": (196, 255, 0),
  "Yellow Tint 2, Nano": (128, 255, 0),
  "Yellow Tint 3": (64, 255, 0),
  "Green": (0, 255, 0),
  "Green Tint 1": (0, 255, 64),
  "Green Tint 2, Emerald": (0, 255, 128),
  "Green Tint 3, Turquoise": (0, 255, 196),
  "Cyan": (0, 255, 255),
  "Cyan Tint 1": (0, 196, 255),
  "Cyan Tint 2": (0, 128, 255),
  "Cyan Tint 3": (0, 64, 255),
  "Blue": (0, 0, 255),
  "Purple Tint 1, Mixer": (64, 0, 255),
  "Purple Tint 2, İndigo": (128, 0, 255),
  "Purple Tint 3, Violet": (194, 0, 255),
  "Magenta": (255, 0, 255),
  "Pink Tint 1, Fuchsia": (255, 0, 196),
  "Pink Tint 2": (255, 0, 128),
  "Pink Tint 3": (255, 0, 64),

  "Maroon": (128, 0, 0),
  "Burgundy": (64, 0, 0),
  "Brown": (128, 64, 0),
  "Beige": (210, 210, 196),
  "Baby Yellow": (255, 255, 196),
  "Ochre": (64, 64, 0),
  "Olive": (64, 128, 0),
  "Mustard": (128, 128, 0),
  "Mint Green": (0, 128, 0),
  "Dark Green": (0, 64, 0),
  "Teal": (0, 196, 128),
  "Dark Blue": (0, 0, 64),
  "Sky": (64, 128, 196),
  "Navy": (0, 0, 128),
  "Lavender": (0, 64, 196),
  "Mauve": (0, 96, 255),
  "Lilac": (196, 128, 255),
  "Rose": (255, 128, 196),
  "Raspberry": (255, 196, 196),
  "Rust": (196, 64, 0),
  "Coral": (196, 128, 64),
  "Mango": (196, 128, 0),
  "Crimson": (64, 24, 24),
  "Moss": (64, 128, 64),
  "Lime": (64, 255, 64),
  "Aqua": (64, 196, 196),
  "Baby Blue": (196, 196, 255),
  "Granite": (64, 64, 128),
  "Grape": (128, 128, 196),
  "Taupe": (196, 164, 128),
  "Resene Ash Brown": (80, 64, 36),
  "Storm": (148, 148, 136),
  "Light Yellow": (196, 196, 64),
  "Light Magenta": (196, 64, 196),
  }

font_lang_support = {
  "Agency FB": ["LA"],
  "Algerian": ["LA"],
  "Arabic Type Setting": ["LA", "", "", "AR"],
  "Arial": ["LA", "GR", "CY"],
  "Arial Black": ["LA", "GR", "CY"],
  "Arial Rounded": ["LA"],
  "Aldhabi": ["LA", "", "", "AR"],
  "Andalus": ["LA", "", "", "AR"],
  "Bahnschrift": ["LA", "GR", "CY"],
  "Baskerville Oldface": ["LA"],
  "Bauhaus 93": ["LA"],
  "Bell": ["LA"],
  "Berlin Sans FB": ["LA"],
  "Berlin Sans FBDemi": ["LA"],
  "Bernard Condensed": ["LA"],
  "Bizud Gothic": ["LA", "GR", "CY", "", "JP"],
  "Bizud Mincho Medium": ["LA", "GR", "CY", "", "JP"],
  "Black Adder ITC": ["LA"],
  "Bodoni": ["LA"],
  "Bodoni Black": ["LA"],
  "Bodoni Poster Compressed": ["LA"],
  "Bookman Oldstyle": ["LA", "GR", "CY"],
  "Book Antiqua": ["LA", "GR", "CY"],
  "Bradley Hand ITC": ["LA"],
  "Britannic": ["LA"],
  "Broadway": ["LA"],
  "Brush Script": ["LA"],
  "Calibri": ["LA", "GR", "CY", "AR"],
  "Californian FB": ["LA"],
  "Calisto": ["LA"],
  "Cambria": ["LA", "GR", "CY"],
  "Cambria Math": ["LA", "GR", "CY"],
  "Candara": ["LA", "GR", "CY"],
  "Cascadi Amono Regular": ["LA", "GR", "CY"],
  "Castellar": ["LA"],
  "Centaur": ["LA"],
  "Century": ["LA", "GR", "CY"],
  "Century Gothic": ["LA", "GR", "CY"],
  "Century School Book": ["LA"],
  "Chiller": ["LA"],
  "Colonna": ["LA"],
  "Comic Sans MS": ["LA", "GR", "CY"],
  "Consolas": ["LA", "GR", "CY"],
  "Constantia": ["LA", "GR", "CY"],
  "Cooperblack": ["LA"],
  "Copperplate Gothic": ["LA"],
  "Corbel": ["LA", "GR", "CY"],
  "Courier New": ["LA", "GR", "CY", "AR"],
  "Curlz": ["LA"],
  "Dubai": ["LA", "", "", "AR"],
  "Dubai Medium": ["LA", "", "", "AR"],
  "Dubai Regular": ["LA", "", "", "AR"],
  "Ebrima": ["LA"],
  "Elephant": ["LA"],
  "Engravers": ["LA"],
  "Eras ITC": ["LA"],
  "Eras Demi ITC": ["LA"],
  "Eras Medium ITC": ["LA"],
  "Extra": [],
  "Felix Titling": ["LA"],
  "Footlight": ["LA"],
  "Forte": ["LA"],
  "Franklin Gothic Book": ["LA", "GR", "CY"],
  "Franklin Gothic Demi": ["LA", "GR", "CY"],
  "Franklin Gothic Demicond": ["LA", "GR", "CY"],
  "Franklin Gothic Heavy": ["LA", "GR", "CY"],
  "Franklin Gothic Medium": ["LA", "GR", "CY"],
  "Franklin Gothic Mediumcond": ["LA", "GR", "CY"],
  "Freestyle Script": ["LA"],
  "French Script": ["LA"],
  "Gabriola": ["LA", "GR", "CY"],
  "Gadugi": ["LA"],
  "Garamond": ["LA", "GR", "CY"],
  "Georgia": ["LA", "GR", "CY"],
  "Gigi": ["LA"],
  "Gill Sans": ["LA"],
  "Gill Sans Extcondensed": ["LA"],
  "Gill Sans Ultra": ["LA"],
  "Gloucester Extra Condensed": ["LA"],
  "Goudystout": ["LA"],
  "Goudy Old Style": ["LA"],
  "Haetten Schweiler": ["LA", "GR", "CY"],
  "Harlow Solid": ["LA"],
  "Harrington": ["LA"],
  "High Tower Text": ["LA"],
  "Holomdl2assets": [],
  "Informal Roman": ["LA"],
  "Impact": ["LA", "GR", "CY"],
  "Imprint Shadow": ["LA"],
  "Inkfree": ["LA", "GR", "CY"],
  "Javanese Text": ["LA"],
  "Jokerman": ["LA"],
  "Juice ITC": ["LA"],
  "Kristen ITC": ["LA"],
  "Kunstler Script": ["LA"],
  "Leelawadee UI": ["LA"],
  "Lucida Bright": ["LA"],
  "Lucida Calligraphy": ["LA"],
  "Lucida Console": ["LA", "GR", "CY"],
  "Lucida Fax": ["LA"],
  "Lucida Fax Regular": ["LA"],
  "Lucida Sans": ["LA", "GR", "CY"],
  "Lucida Sans Regular": ["LA"],
  "Lucida Sans Roman": ["LA"],
  "Lucida Sans Typewriter Oblique": ["LA"],
  "Magneto": ["LA"],
  "Mai and Ragd": ["LA"],
  "Matura Script Capitals": ["LA"],
  "Malgun Gothic": ["LA", "GR", "CY", "", "JP", "KO"],
  "Malgun Gothic Semilight": ["LA", "GR", "CY", "", "JP", "KO"],
  "Meiryo": ["LA", "GR", "CY", "", "JP"],
  "Meiryo UI": ["LA", "GR", "CY", "", "JP"],
  "Microsoft Himalaya": ["LA"],
  "Microsoft Jhenghei": ["LA", "GR", "CY", "", "JP"],
  "Microsoft New Tailue": ["LA"],
  "Microsoft Phagspa": ["LA"],
  "Microsoft Sans Serif": ["LA", "GR", "CY", "AR"],
  "Microsoft Taile": ["LA"],
  "Microsoft Uighur": ["LA", "", "", "AR"],
  "Microsoft Yahei": ["LA", "GR", "CY", "", "JP"],
  "Microsoft Yibaiti": ["LA"],
  "Mingliuextb": ["LA"],
  "Mistral": ["LA", "GR", "CY"],
  "Modernno 20": ["LA"],
  "Mongolian Baiti": ["LA"],
  "Monotype Corsiva": ["LA", "GR", "CY"],
  "MS Gothic": ["LA", "GR", "CY", "", "JP"],
  "MS Mincho": ["LA", "GR", "CY", "", "JP"],
  "MS Outlook": [],
  "MS Reference Sans Serif": ["LA", "GR", "CY"],
  "MS Reference Specialty": [],
  "MV Boli": ["LA"],
  "Myanmar Text": ["LA"],
  "Niagara Engraved": ["LA"],
  "Niagara Solid": ["LA"],
  "Nirmala UI": ["LA"],
  "Nirmala UI Semilight": ["LA"],
  "NSimsun": ["LA", "GR", "CY", "", "JP"],
  "Palace Script": ["LA"],
  "Palatinolino Type": ["LA", "GR", "CY"],
  "Papyrus": ["LA"],
  "Parchment": ["LA"],
  "Perpetua": ["LA"],
  "Perpetua Titling": ["LA"],
  "Playbill": ["LA"],
  "Poor Richard": ["LA"],
  "Pristina": ["LA"],
  "Ocra Extended": ["LA"],
  "Old English Text": ["LA"],
  "Onyx": ["LA"],
  "Rage": ["LA"],
  "Ravie": ["LA"],
  "Retroville NC": ["LA", "", "CY"],
  "Rockwell": ["LA"],
  "Rockwell Condensed": ["LA"],
  "Rockwell Extra": ["LA"],
  "Sakkalmajalla": ["LA", "", "", "AR"],
  "Sans Serif Collection": [],
  "Script": ["LA"],
  "Segoe Fluent Icons": [],
  "Segoe UI": ["LA", "GR", "CY", "AR"],
  "Segoe UI Black": ["LA", "GR", "CY"],
  "Segoe UI Emoji": ["LA"],
  "Segoe UI Fluent Icons": ["LA", "GR", "CY"],
  "Segoe UI Historic": ["LA"],
  "Segoe UI Semibold": ["LA", "GR", "CY", "AR"],
  "Segoe UI Semilight": ["LA", "GR", "CY", "AR"],
  "Segoe UI Symbol": ["LA", "GR"],
  "Segoe UI Variable": ["LA", "GR", "CY"],
  "Serif": ["LA", "GR", "CY"],
  "Showcard Gothic": ["LA"],
  "Simplified Arabic": ["LA", "", "", "AR"],
  "Simplified Arabic Fixed": ["LA", "", "", "AR"],
  "Simsun": ["LA", "GR", "CY"],
  "Simsun EXTB": ["LA"],
  "Sitkatext": ["LA", "GR", "CY"],
  "Snap ITC": ["LA"],
  "Stencil": ["LA"],
  "Sylfaen": ["LA", "GR", "CY"],
  "Symbol": ["", "GR"],
  "Tahoma": ["LA", "GR", "CY", "AR"],
  "Tempus Sans ITC": ["LA"],
  "Times New Roman": ["LA", "GR", "CY", "AR"],
  "Traditional Arabic": ["LA", "", "", "AR"],
  "Trebuchet MS": ["LA", "GR", "CY"],
  "Twcen": ["LA"],
  "Twcen Condensed": ["LA"],
  "Uddigi Kyokashonb": ["LA", "GR", "CY", "", "JP"],
  "Uddigi Kyokashonkb": ["LA", "GR", "CY", "", "JP"],
  "Uddigi Kyokashonpb": ["LA", "GR", "CY", "", "JP"],
  "Uddigi Kyokashonpr": ["LA", "GR", "CY", "", "JP"],
  "Uddigi Kyokashonr": ["LA", "GR", "CY", "", "JP"],
  "Urdu Type Setting": ["LA", "", "", "AR"],
  "Vera Serif": ["LA", "GR", "CY", "AR"],
  "Verdana": ["LA", "GR", "CY"],
  "Vinerhand Itc": ["LA"],
  "Vivaldi": ["LA"],
  "Vladimir Script": ["LA"],
  "Webdings": ["", "", "", "", "", "", "??"],
  "Wide Latin": ["LA"],
  "Wingdings": ["", "", "", "", "", "", "??"],
  "Wingdings 2": ["", "", "", "", "", "", "??"],
  "Wingdings 3": ["", "", "", "", "", "", "??"],
  "Yu Gothic": ["LA", "GR", "CY", "", "JP"],
  "Yu Gothic Medium": ["LA", "GR", "CY", "", "JP"],
  "Yu Gothic Regular": ["LA", "GR", "CY", "", "JP"],
  "Yu Gothic UI": ["LA", "GR", "CY", "", "JP"],
  "Yu Gothic UI Semibold": ["LA", "GR", "CY", "", "JP"],
  "Yu Gothic UI Semilight": ["LA", "GR", "CY", "", "JP"],
  "Yu Gothic UI Regular": ["LA", "GR", "CY", "", "JP"],
  "Yumincho": ["LA", "GR", "CY", "", "JP"],
}



#("عرابيً", "AR")

languages = (("English", "EN"), ("Assets/editor/LAUNCHER Arabic.png", "AR"), ("Türkçe", "TR"), ("日本語", "JP"), ("Nederlands", "NL"))


l = {
  "EN": {
    "": "",
    "Load Game": "Load Game",
    "Save Game State": "Save Game State",
    "Load Game State": "Load Game State",
    "Restart Game": "Restart Game",
    "Eject": "Eject",
    "Switch to Editor": "Switch to Editor",
    "Power Off": "Power Off",

    "Configure...": "Configure...",
    "Settings": "Settings",
    "Miscellaneous": "Miscellaneous",
    "Open Terminal": "Open Terminal",
    "Toggle Debug Mode": "Toggle Debug Mode",
    "Load Additional Packages": "Load Additional Packages",
    "Refresh": "Refresh",
    "Retry": "Retry",

    "Profile": "Profile",
    "Host Server": "Host Server",
    "Connect to Server": "Connect to Server",
    "Performance": "Performance",

    "Input": "Input",
    "Video": "Video",
    "Audio": "Audio",
    "Set Device": "Set Device",
    "Set Deadzone": "Set Deadzone",
    "Refresh Connections": "Refresh Connections",
    "Rumble: ": "Rumble: ",
    "Render Filter": "Render Filter",
    "Color Swizzle": "Color Swizzle",
    "Set Render Mode": "Set Render Mode",
    
    "Network Monitor": "Network Monitor",


    "Add Instance": "Add Instance",
    "Delete Object": "Delete Object",
    "Edit Object": "Edit Object",
    "Manage Rooms": "Manage Rooms",
    "Add Cutscene": "Add Cutscene",
    "General Game Settings": "General Game Settings",
    "Playtest": "Playtest",
    "Stop Playtest": "Stop Playtest",
    "Save Game": "Save Game",
    "Load Game": "Load Game",
    "No cutscenes in this room": "No cutscenes in this room",
    "No object selected": "No object selected",
    "Selected Object: ": "Selected Object: ",
    "İn Room: ": "İn Room: ",
    "Tunaditor": "Tunaditor",
    "Scroll X: ": "Scroll X: ",
    "Scroll Y: ": "Scroll Y: ",
    "Toggle Show/Hide": "Toggle Show/Hide",
    "Access Layer L": "Access Layer L",
    "Edit Cutscene": "Edit Cutscene",
    "Rename Cutscene": "Rename Cutscene",
    "Delete Cutscene": "Delete Cutscene",
    "Are you sure you want to leave?": "Are you sure you want to leave?",
    "Back to Editing": "Back to Editing",
    "Save and Quit": "Save and Quit",
    "Quit without Saving": "Quit without Saving",

    "New Player": "New Player",
    "New Layer": "New Layer",
    "New Entity Type": "New Entity Type",
    "New Collectible Type": "New Collectible Type",
    "New Background Layer": "New Background Layer",
    "New Zone": "New Zone",
    "New Text": "New Text",
    "Select Instance": "Select Instance",
    "Select Instance Type": "Select Instance Type",
    "Select Background Layer": "Select Background Layer",
    "ESC to Cancel": "ESC to Cancel",
    "Create Object": "Create Object",

    "Toggle Behavior": "Toggle Behavior",
    "Next Page": "Next Page",
    "Decrease": "Decrease",
    "Increase": "Increase",
    "Decrease Decimal": "Decrease Decimal",
    "Increase Decimal": "Increase Decimal",
    "Use Stat": "Use Stat",
    "Finish Entity Type": "Finish Entity Type",

    "Game Statistics": "Game Statistics",
    "Statistics and İnventory": "Statistics and İnventory",
    "Set Game Style": "Set Game Style",
    "Ports and Devices": "Ports and Devices",
    "Customize Controls for Inputs and Events": "Customize Controls for Inputs and Events",
    "Application Settings": "Application Settings",
    "Control the Resolution and FPS": "Control the Resolution and FPS",
    "General Settings": "General Settings",
    "Set Up Tile Size": "Set Up Tile Size",

    "Display Settings": "Display Settings",
    "Change Display": "Change Display",
    "Change FPS": "Change FPS",
    "Use DT: ": "Use DT: ",
    "Enter Game Publisher": "Enter Game Publisher",

    "Go Back": "Go Back",
    "Go Back.": "Go Back.",
    "Rename": "Rename",
    "Add Room": "Add Room",
    "Edit Room": "Edit Room",
    "Rename Room": "Rename Room",
    "Delete Room": "Delete Room",
    "Create Door to This Room": "Create Door to This Room",
    "Edit Room's Menu": "Edit Room's Menu",
    "Room Manager": "Room Manager",
    "Borders": "Borders",
    "Right: ": "Right: ",
    "Left: ": "Left: ",
    "Top: ": "Top: ",
    "Bottom: ": "Bottom: ",
    "Total Cutscenes: ": "Total Cutscenes: ",
    "Total Actors: ": "Total Actors: ",
    "Total Layers: ": "Total Layers: ",
    "Track: ": "Track: ",
    "Move Up": "Move Up",
    "Move Down": "Move Down",

    "Page": "Page",
    "Press L (-) and R (+) to Access More Glyphs:": "Press L (-) and R (+) to Access More Glyphs:",
    "Press ENTER to Confirm, ESC to Cancel": "Press ENTER to Confirm, ESC to Cancel",

    "Room: ": "Room: ",
    "Play Track (First)": "Play Track (First)",
    "Play Track (Loop)": "Play Track (Loop)",
    "Play Track": "Play Track",
    "Browse Tracks (First)": "Browse Tracks (First)",
    "Browse Tracks (Loop)": "Browse Tracks (Loop)",
    "Stop Track": "Stop Track",
    "Browse SFX": "Browse SFX",
    "Change Border": "Change Border",
    "Right Border": "Right Border",
    "Left Border": "Left Border",
    "Top Border": "Top Border",
    "Bottom Border": "Bottom Border",
    "Scrolling Mode: ": "Scrolling Mode: ",
    "Hide Players in This Room": "Hide Players in This Room",
    "Apply Shader": "Apply Shader",
    "Shader: ": "Shader: ",
    "No Scrolling": "No Scrolling",
    "Default Scrolling": "Default Scrolling",
    "Rounded Scrolling": "Rounded Scrolling",
    "Focus on Center": "Focus on Center",
    "Horizontal Mirror": "Horizontal Mirror",
    "Vertical Mirror": "Vertical Mirror",
    "Gravity": "Gravity",
    "Decrease Gravity": "Decrease Gravity",
    "İncrease Gravity": "İncrease Gravity",
    "Token": "Token",
    "Mode": "Mode",
    "Decrease Uİ Token": "Decrease Uİ Token",
    "İncrease Uİ Token": "İncrease Uİ Token",
    "Decrease Uİ Mode": "Decrease Uİ Mode",
    "İncrease Uİ Mode": "İncrease Uİ Mode",
    "Add to Show": "Add to Show",
    "Add to Hide": "Add to Hide",
    "Uİ Tokens to Show: ": "Uİ Tokens to Show: ",
    "Uİ Tokens to Hide: ": "Uİ Tokens to Hide: ",
    "Tokens Set to Mode (T, M): ": "Tokens Set to Mode (T, M): ",
    "Set Mode for Selected Token": "Set Mode for Selected Token",
    "Press L (-) and R (+) to Access More Settings:": "Press L (-) and R (+) to Access More Settings:",
    "Add Track": "Add Track",
    "Remove Track": "Remove Track",
    "Gameplay Mode: ": "Gameplay Mode: ",
    "Platformer": "Platformer",
    "Top-Down": "Top-Down",

    "Layer Options": "Layer Options",
    "Collectibles": "Collectibles",
    "Actors": "Actors",
    "Toggle Solidity": "Toggle Solidity",
    "Toggle Slipperiness": "Toggle Slipperiness",
    "Toggle Flatness": "Toggle Flatness",
    "Set Label": "Set Label",
    "Closer": "Closer",
    "Further": "Further",
    "Dimmer": "Dimmer",
    "Brighter": "Brighter",
    "Delete Layer": "Delete Layer",
    "Display Resolution and Tile Size do not Match Up!": "Display Resolution and Tile Size do not Match Up!",
    
    "Add Sound Effect": "Add Sound Effect",
    "Play Sound Effect": "Play Sound Effect",
    "Remove Sound Effect": "Remove Sound Effect",
    "Browse SFXs": "Browse SFXs",
    "Delete Collectible Type Object": "Delete Collectible Type Object",
    "Add Background Layer": "Add Background Layer",
    "Delete Background": "Delete Background",
    "Repeat X": "Repeat X",
    "Repeat Y": "Repeat Y",
    "Toggle X Scroll": "Toggle X Scroll",
    "Toggle Y Scroll": "Toggle Y Scroll",
    "Horizontal Mirroring": "Horizontal Mirroring",
    "Vertical Mirroring": "Vertical Mirroring",
    "Move Front": "Move Front",
    "Move Back": "Move Back",
    "Toggle Foreground": "Toggle Foreground",
    "Set Background to Player Character": "Set Background to Player Character",
    "Copy Image Path of Background": "Copy Image Path of Background",
    "Decrease X Speed": "Decrease X Speed",
    "İncrease X Speed": "İncrease X Speed",
    "Decrease Y Speed": "Decrease Y Speed",
    "İncrease Y Speed": "İncrease Y Speed",
    "Decrease X": "Decrease X",
    "İncrease X": "İncrease X",
    "Decrease Y": "Decrease Y",
    "İncrease Y": "İncrease Y",
    "Decrease X Speed/Destination": "Decrease X Speed/Destination",
    "İncrease X Speed/Destination": "İncrease X Speed/Destination",
    "Decrease Y Speed/Destination": "Decrease Y Speed/Destination",
    "İncrease Y Speed/Destination": "İncrease Y Speed/Destination",

    "Set Dialogue": "Set Dialogue",
    "Delete Dialogue": "Delete Dialogue",
    
    "Set Text": "Set Text",







  },
  
  "AR": {
    "": "",
    "Load Game": "تَحمِيل اللُّعبة",
    "Save Game State": "حِفظ حالة اللُّعبة",
    "Load Game State": "تَحمِيل حالة اللُّعبة",
    "Restart Game": "إعَادة تَشغِيل اللُّعبة",
    "Eject": "إخْرَاج",
    "Switch to Editor": "التَّحويل إلى المُحرِّر",
    "Power Off": "إيقَاف التَّشغيل",

    "Configure...": "تَهيِئة...",
    "Settings": "الإعدادات",
    "Miscellaneous": "مُتَنَوِّعَات",
    "Open Terminal": "فَتْح الطَّرفِيَّة",
    "Toggle Debug Mode": "تَبدِيل وضع تَصْحيح الأخْطاء",
    "Load Additional Packages": "Load Additional Packages",
    "Refresh": "Refresh",
    "Retry": "Retry",

    "Profile": "Profil",
    "Host Server": "استِضَافة خادِم",
    "Connect to Server": "الاتِّصَال بالخادِم",
    "Performance": "الأداء",

    "Input": "الإدخال",
    "Video": "الفيديو",
    "Audio": "الصَّوت",
    "Set Device": "تَعيِين الجِهاز",
    "Set Deadzone": "تَعيِين المنطقة الميتة",
    "Refresh Connections": "تَحدِيث الاتِّصالات",
    "Rumble: ": "الارتِجَاف: ",
    "Render Filter": "مُرشِّح التَّصوِير",
    "Color Swizzle": "مُبَادَلة الألوان",
    "Set Render Mode": "تَعيِين وضع التَّصوِير",

    "Network Monitor": "مُراقِب الشَّبَكة",


    "Add Instance": "Add Instance",
    "Delete Object": "Delete Object",
    "Edit Object": "Edit Object",
    "Manage Rooms": "Manage Rooms",
    "Add Cutscene": "Add Cutscene",
    "General Game Settings": "General Game Settings",
    "Playtest": "Playtest",
    "Stop Playtest": "Stop Playtest",
    "Save Game": "Save Game",
    "Load Game": "تَحمِيل اللُّعبة",
    "No cutscenes in this room": "No cutscenes in this room",
    "No object selected": "No object selected",
    "Selected Object: ": "Selected Object: ",
    "İn Room: ": "İn Room: ",
    "Tunaditor": "Tunaditor",
    "Scroll X: ": "Scroll X: ",
    "Scroll Y: ": "Scroll Y: ",
    "Toggle Show/Hide": "Toggle Show/Hide",
    "Access Layer L": "Access Layer L",
    "Edit Cutscene": "Edit Cutscene",
    "Rename Cutscene": "Rename Cutscene",
    "Delete Cutscene": "Delete Cutscene",
    "Are you sure you want to leave?": "Are you sure you want to leave?",
    "Back to Editing": "Back to Editing",
    "Save and Quit": "Save and Quit",
    "Quit without Saving": "Quit without Saving",

    "New Player": "New Player",
    "New Layer": "New Layer",
    "New Entity Type": "New Entity Type",
    "New Collectible Type": "New Collectible Type",
    "New Background Layer": "New Background Layer",
    "New Zone": "New Zone",
    "New Text": "New Text",
    "Select Instance": "Select Instance",
    "Select Instance Type": "Select Instance Type",
    "Select Background Layer": "Select Background Layer",
    "ESC to Cancel": "ESC to Cancel",
    "Create Object": "Create Object",

    "Toggle Behavior": "Toggle Behavior",
    "Next Page": "Next Page",
    "Decrease": "Decrease",
    "Increase": "Increase",
    "Decrease Decimal": "Decrease Decimal",
    "Increase Decimal": "Increase Decimal",
    "Use Stat": "Use Stat",
    "Finish Entity Type": "Finish Entity Type",

    "Game Statistics": "Game Statistics",
    "Statistics and İnventory": "Statistics and İnventory",
    "The Game Style": "The Game Style",
    "Set Game Style": "Set Game Style",
    "Ports and Devices": "Ports and Devices",
    "Customize Controls for Inputs and Events": "Customize Controls for Inputs and Events",
    "Application Settings": "Application Settings",
    "Control the Resolution and FPS": "Control the Resolution and FPS",
    "General Settings": "General Settings",
    "Set Up Tile Size": "Set Up Tile Size",

    "Display Settings": "Display Settings",
    "Change Display": "Change Display",
    "Change FPS": "Change FPS",
    "Use DT: ": "Use DT: ",

    "Go Back": "Go Back",
    "Add Room": "Add Room",
    "Edit Room": "Edit Room",
    "Rename Room": "Rename Room",
    "Delete Room": "Delete Room",
    "Create Door to This Room": "Create Door to This Room",
    "Edit Room's Menu": "Edit Room's Menu",
    "Room Manager": "Room Manager",
    "Borders": "Borders",
    "Right: ": "Right: ",
    "Left: ": "Left: ",
    "Top: ": "Top: ",
    "Bottom: ": "Bottom: ",
    "Total Cutscenes: ": "Total Cutscenes: ",
    "Total Actors: ": "Total Actors: ",
    "Total Layers: ": "Total Layers: ",
    "Track: ": "Track: ",
    "Move Up": "Move Up",
    "Move Down": "Move Down",

    "Page": "Page",
    "Press L (-) and R (+) to Access More Glyphs:": "Press L (-) and R (+) to Access More Glyphs:",
    "Press ENTER to Confirm, ESC to Cancel": "Press ENTER to Confirm, ESC to Cancel",

    "Room: ": "Room: ",
    "Play Track (First)": "Play Track (First)",
    "Play Track (Loop)": "Play Track (Loop)",
    "Browse Tracks (First)": "Browse Tracks (First)",
    "Browse Tracks (Loop)": "Browse Tracks (Loop)",
    "Stop Track": "Stop Track",
    "Browse SFX": "Browse SFX",
    "Change Border": "Change Border",
    "Right Border": "Right Border",
    "Left Border": "Left Border",
    "Top Border": "Top Border",
    "Bottom Border": "Bottom Border",
    "Scrolling Mode: ": "Scrolling Mode: ",
    "Hide Players in This Room": "Hide Players in This Room",
    "Apply Shader": "Apply Shader",
    "Shader: ": "Shader: ",
    "No Scrolling": "No Scrolling",
    "Default Scrolling": "Default Scrolling",
    "Rounded Scrolling": "Rounded Scrolling",
    "Focus on Center": "Focus on Center",
    "Horizontal Mirror": "Horizontal Mirror",
    "Vertical Mirror": "Vertical Mirror",
    "Gravity": "Gravity",
    "Decrease Gravity": "Decrease Gravity",
    "İncrease Gravity": "İncrease Gravity",
    "Token": "Token",
    "Mode": "Mode",
    "Decrease Uİ Token": "Decrease Uİ Token",
    "İncrease Uİ Token": "İncrease Uİ Token",
    "Decrease Uİ Mode": "Decrease Uİ Mode",
    "İncrease Uİ Mode": "İncrease Uİ Mode",
    "Add to Show": "Add to Show",
    "Add to Hide": "Add to Hide",
    "Uİ Tokens to Show: ": "Uİ Tokens to Show: ",
    "Uİ Tokens to Hide: ": "Uİ Tokens to Hide: ",
    "Tokens Set to Mode (T, M): ": "Tokens Set to Mode (T, M): ",
    "Set Mode for Selected Token": "Set Mode for Selected Token",
    "Press L (-) and R (+) to Access More Settings:": "Press L (-) and R (+) to Access More Settings:",
    "Add Track": "Add Track",
    "Remove Track": "Remove Track",
    "Gameplay Mode: ": "Gameplay Mode: ",
    "Platformer": "Platformer",
    "Top-Down": "Top-Down",

    "Layer Options": "Layer Options",
    "Collectibles": "Collectibles",
    "Actors": "Actors",
    "Toggle Solidity": "Toggle Solidity",
    "Toggle Slipperiness": "Toggle Slipperiness",
    "Toggle Flatness": "Toggle Flatness",
    "Set Label": "Set Label",
    "Closer": "Closer",
    "Further": "Further",
    "Dimmer": "Dimmer",
    "Brighter": "Brighter",
    "Delete Layer": "Delete Layer",
    "Display Resolution and Tile Size do not Match Up!": "Display Resolution and Tile Size do not Match Up!",
    
    "Add Sound Effect": "Add Sound Effect",
    "Play Sound Effect": "Play Sound Effect",
    "Remove Sound Effect": "Remove Sound Effect",
    "Browse SFXs": "Browse SFXs",
    "Delete Collectible Type Object": "Delete Collectible Type Object",
    "Add Background Layer": "Add Background Layer",
    "Delete Background": "Delete Background",
    "Repeat X": "Repeat X",
    "Repeat Y": "Repeat Y",
    "Toggle X Scroll": "Toggle X Scroll",
    "Toggle Y Scroll": "Toggle Y Scroll",
    "Horizontal Mirroring": "Horizontal Mirroring",
    "Vertical Mirroring": "Vertical Mirroring",
    "Move Front": "Move Front",
    "Move Back": "Move Back",
    "Toggle Foreground": "Toggle Foreground",
    "Set Background to Player Character": "Set Background to Player Character",
    "Copy Image Path of Background": "Copy Image Path of Background",
    "Decrease X Speed": "Decrease X Speed",
    "İncrease X Speed": "İncrease X Speed",
    "Decrease Y Speed": "Decrease Y Speed",
    "İncrease Y Speed": "İncrease Y Speed",
    "Decrease X": "Decrease X",
    "İncrease X": "İncrease X",
    "Decrease Y": "Decrease Y",
    "İncrease Y": "İncrease Y",
    "Decrease X Speed/Destination": "Decrease X Speed/Destination",
    "İncrease X Speed/Destination": "İncrease X Speed/Destination",
    "Decrease Y Speed/Destination": "Decrease Y Speed/Destination",
    "İncrease Y Speed/Destination": "İncrease Y Speed/Destination",
  },







  "TR": {
    "": "",
    "Load Game": "Oyun Yükle",
    "Save Game State": "Oyun Kayıt Kaydet",
    "Load Game State": "Oyun Kayıt Yükle",
    "Restart Game": "Yeniden Başlat",
    "Eject": "Diski Çıkart",
    "Switch to Editor": "Tunaditör'e Dön",
    "Power Off": "Kapat",

    "Configure...": "Tercihler...",
    "Settings": "Ayarlar",
    "Miscellaneous": "Cihaz Türü",
    "Open Terminal": "Konsolu Aç",
    "Toggle Debug Mode": "Debug Mod",
    "Load Additional Packages": "Ek Paketleri Yükle",
    "Refresh": "Yeniden Yükle",
    "Retry": "Yeniden Dene",

    "Profile": "Profil",
    "Host Server": "Server Başlat",
    "Connect to Server": "Servere Bağla",
    "Performance": "Performans",

    "Input": "Giriş",
    "Video": "Görüntü",
    "Audio": "Ses",
    "Set Device": "Cihazı Ayarla",
    "Set Deadzone": "Deadzone Ayarla",
    "Refresh Connections": "Bağlatıları Yeniden Yükle",
    "Rumble: ": "Titriş: ",
    "Render Filter": "Meyda Filtre",
    "Color Swizzle": "Renk Sıralama",
    "Set Render Mode": "Media Mod",

    "Network Monitor": "İnternet Monitörü",


    "Add Instance": "Nesne Ekle",
    "Delete Object": "Nesneyi Sil",
    "Edit Object": "Nesneyi Ayarla",
    "Manage Rooms": "Odalar",
    "Add Cutscene": "Filim Ekle",
    "General Game Settings": "Genel Oyun Ayarlar",
    "Playtest": "Oyna",
    "Stop Playtest": "Oyun Modu Dur",
    "Save Game": "Oyun Kaydet",
    "Load Game": "Oyun Yükle",
    "No cutscenes in this room": "Bu odada filimler yok",
    "No object selected": "Hiç nesne seçilmemiş",
    "Selected Object: ": "Seçilmiş Nesne: ",
    "İn Room: ": "Oda: ",
    "Tunaditor": "Tunaditör",
    "Scroll X: ": "Skrol X: ",
    "Scroll Y: ": "Skrol Y: ",
    "Toggle Show/Hide": "Göster/Gizle",
    "Access Layer L": "Katmana Gir L",
    "Edit Cutscene": "Filimi Özelleştir",
    "Rename Cutscene": "Filimi Yeniden Adlandır",
    "Delete Cutscene": "Filimi Sil",
    "Are you sure you want to leave?": "Gerçekten çıkmaya emin misin?",
    "Back to Editing": "Hayır, Geri Dön",
    "Save and Quit": "Evet, kaydet ve çık",
    "Quit without Saving": "Evet, kaydetmeden çık",

    "Toggle Behavior": "Aç/Kapat",
    "Next Page": "İleri",
    "Decrease": "Azalt",
    "Increase": "Arttır",
    "Decrease Decimal": "Desimalı Azalt",
    "Increase Decimal": "Desimalı Arttır",
    "Use Stat": "İstatistiği Kullan",
    "Finish Entity Type": "Compleet Entity Type",
    
    "New Player": "Yeni Oyuncu",
    "New Layer": "Yeni Katman",
    "New Entity Type": "Yeni NPC Tür",
    "New Collectible Type": "Yeni Eşya Tür",
    "New Background Layer": "Yeni Arkaplan",
    "New Zone": "Yeni Bölge",
    "New Text": "Yeni Metni",
    "Select Instance": "Nesniyi Seç",
    "Select Instance Type": "Nesni Türü Seç",
    "Select Background Layer": "Select Arkaplan Katman",
    "ESC to Cancel": "Vazgeçmek için ESC",
    "Create Object": "Nesne Ekle",

    "Game Statistics": "Oyun İstatistikler",
    "Statistics and İnventory": "İstatistikler ve Envanter",
    "Set Game Style": "Oyun Stili Ayarla",
    "Ports and Devices": "Portlar ve Cihazlar",
    "Customize Controls for Inputs and Events": "Kontrollar Özelleştir",
    "Application Settings": "Uygulama Ayarlar",
    "Control the Resolution and FPS": "Ekran Boyut vs FPS",
    "General Settings": "Genel Ayarlar",
    "Set Up Tile Size": "Blok Büyüklük",

    "Display Settings": "Ekran Ayarlar",
    "Change Display": "Ekranı Ayarla",
    "Change FPS": "FPS'i Ayarla",
    "Use DT: ": "DeltaTime: ",

    "Go Back": "Geri Dön",
    "Add Room": "Yeni Oda Ekle",
    "Edit Room": "Odayı Ayarla",
    "Rename Room": "Odayı Yeniden Adlandır",
    "Delete Room": "Odayı Sil",
    "Create Door to This Room": "Bu Odaya Götüren bir Kapı Ekle",
    "Edit Room's Menu": "Odanin Menüsünü Ayarla",
    "Room Manager": "Odalar",
    "Borders": "Sınırlar",
    "Right: ": "Sağ: ",
    "Left: ": "Sol: ",
    "Top: ": "Üst: ",
    "Bottom: ": "Alt: ",
    "Total Cutscenes: ": "Filim Sayı: ",
    "Total Actors: ": "NPC Sayı: ",
    "Total Layers: ": "Katman Sayı: ",
    "Track: ": "Şarkı: ",
    "Move Up": "Yukarı Taşı",
    "Move Down": "Aşağı Taşı",

    "Page": "Sayfa",
    "Press L (-) and R (+) to Access More Glyphs:": "Daha çok glifler için L (-) ve R (+)'ye bas:",
    "Press ENTER to Confirm, ESC to Cancel": "Tamamlamak için ENTER'a bas, Vezgeçmek için ESC'e bas",

    "Room: ": "Oda: ",
    "Play Track (First)": "Şarkı Oynat (Birinci)",
    "Play Track (Loop)": "Şarkı Oynat (Loop)",
    "Browse Tracks (First)": "Şarkılara Göz At (Birinci)",
    "Browse Tracks (Loop)": "Şarkılara Göz At (Loop)",
    "Stop Track": "Şarkıyı Durdur",
    "Browse SFX": "Seslere Göz At",
    "Change Border": "Sınır Değiştir",
    "Right Border": "Sağ Sınırı",
    "Left Border": "Sol Sınırı",
    "Top Border": "Üst Sınırı",
    "Bottom Border": "Alt Sınırı",
    "Scrolling Mode: ": "Skrol Modu: ",
    "Hide Players in This Room": "Bu Odada Oyuncuları Gizle",
    "Apply Shader": "Shader Ekle",
    "Shader: ": "Shader: ",
    "No Scrolling": "Skrol Yok",
    "Default Scrolling": "Normal Skrolu",
    "Rounded Scrolling": "Izgaraya Yapış",
    "Focus on Center": "Ortaya Odakla",
    "Horizontal Mirror": "Yatay Ayna",
    "Vertical Mirror": "Dikey Ayna",
    "Gravity": "Yer Çekimi",
    "Decrease Gravity": "Yer Çekimi Azalt",
    "İncrease Gravity": "Yer Çekimi Arttır",
    "Token": "Token",
    "Mode": "Mod",
    "Decrease Uİ Token": "Tokeni Azalt",
    "İncrease Uİ Token": "Tokeni Çoğalt",
    "Decrease Uİ Mode": "Modu Azalt",
    "İncrease Uİ Mode": "Modu Çoğalt",
    "Add to Show": "Uİ Modu Göster",
    "Add to Hide": "Uİ Modu Gizle",
    "Uİ Tokens to Show: ": "Gösteren Uİ Modlar: ",
    "Uİ Tokens to Hide: ": "Gizlenen Uİ Modlar: ",
    "Tokens Set to Mode (T, M): ": "Moda Çeviren Tokenler (T, M): ",
    "Set Mode for Selected Token": "Seçilmiş Token için Moda Ayarla",
    "Press L (-) and R (+) to Access More Settings:": "Daha çok ayarlar için L (-) ve R (+)'ye bas:",
    "Add Track": "Şarkı Ekle",
    "Remove Track": "Şarkı Kaldır",
    "Gameplay Mode: ": "Gameplay Mod: ",
    "Platformer": "Zıplamak",
    "Top-Down": "Üstten-Alta",

    "Layer Options": "Katman Ayarlar",
    "Collectibles": "Eşyalar",
    "Actors": "NPC'ler",
    "Toggle Solidity": "Katı Aç/Kapat",
    "Toggle Slipperiness": "Kaygan Aç/Kapat",
    "Toggle Flatness": "Düz Aç/Kapat",
    "Set Label": "Etiket Tak",
    "Closer": "Daha Yakın",
    "Further": "Daha Uzak",
    "Dimmer": "Daha Kara",
    "Brighter": "Daha Açık",
    "Delete Layer": "Katmanı Sil",
    "Display Resolution and Tile Size do not Match Up!": "Ekranın Boyutu ve Blokun Boyutların arasında Çeliski Var!",
    
    "Add Sound Effect": "Sesi Ekle",
    "Play Sound Effect": "Sesi Oynat",
    "Remove Sound Effect": "Sesi Sil",
    "Browse SFXs": "Sesleri Gör",
    "Delete Collectible Type Object": "Eşya Türü Sil",
    "Add Background Layer": "Arkaplan Katmanı Ekle",
    "Delete Background": "Arkaplanı Sil",
    "Repeat X": "X'ten Tekrarla",
    "Repeat Y": "Y'ten Tekrarla",
    "Toggle X Scroll": "X Skrolu Aç/Kapat",
    "Toggle Y Scroll": "Y Skrolu Aç/Kapat",
    "Horizontal Mirroring": "Yataydan Aynat",
    "Vertical Mirroring": "Dikeyden Aynat",
    "Move Front": "Öne Getir",
    "Move Back": "Arkaya Getir",
    "Toggle Foreground": "En Öne Getir (Önplan)",
    "Set Background to Player Character": "Arkaplanı Oyuncunun Karakterine Koy",
    "Copy Image Path of Background": "Arkaplanın Resimi Dosyanın Adı Kopyala",
    "Decrease X Speed": "X Hızı Azalt",
    "İncrease X Speed": "X Hızı Arttır",
    "Decrease Y Speed": "Y Hızı Azalt",
    "İncrease Y Speed": "X Hızı Arttır",
    "Decrease X": "X'i Azalt",
    "İncrease X": "X'i Arttır",
    "Decrease Y": "Y'ı Azalt",
    "İncrease Y": "Y'ı Arttır",
    "Decrease X Speed/Destination": "X Hızı/Hedefi Azalt",
    "İncrease X Speed/Destination": "X Hızı/Hedefi Arttır",
    "Decrease Y Speed/Destination": "Y Hızı/Hedefi Azalt",
    "İncrease Y Speed/Destination": "X Hızı/Hedefi Arttır",








  },
  "JP": {
    "": "",
    "Load Game": "ロードする",
    "Save Game State": "セーブデータ保存する",
    "Load Game State": "セーブデータロードする",
    "Restart Game": "最初から初め",
    "Eject": "カード出せる",
    "Switch to Editor": "ツナディター",
    "Power Off": "パワーOFF",

    "Configure...": "コンフィグ...",
    "Settings": "設定",
    "Miscellaneous": "情報システム",
    "Open Terminal": "コンソール",
    "Toggle Debug Mode": "ディバグ",
    "Load Additional Packages": "追加パッケージをロードする",
    "Refresh": "アップデート",
    "Retry": "リトライ",

    "Profile": "プロファイル",
    "Host Server": "ホストサーバー",
    "Connect to Server": "サーバーに接続する",
    "Performance": "パフォーマンス",

    "Input": "入力",
    "Video": "ビデオ",
    "Audio": "音",
    "Set Device": "デバイス",
    "Set Deadzone": "デッドゾーン",
    "Refresh Connections": "コネクションアップデート",
    "Rumble: ": "ランボール: ",
    "Render Filter": "フィルター",
    "Color Swizzle": "色スウィズル",
    "Set Render Mode": "レンダリングモード",
    
    "Network Monitor": "ネット",


    "Add Instance": "物体を加えて",
    "Delete Object": "物体を消す",
    "Edit Object": "物体を編集する",
    "Manage Rooms": "ルームを管理する",
    "Add Cutscene": "動画を加えて",
    "General Game Settings": "ゲームの一般的な設定",
    "Playtest": "プレーテスト",
    "Stop Playtest": "プレーテスト止める",
    "Save Game": "ゲームを保存する",
    "Load Game": "ゲームをロードする",
    "No cutscenes in this room": "このルームには動画はない",
    "No object selected": "物体が選択されていない",
    "Selected Object: ": "選択された物体: ",
    "İn Room: ": "ルーム： ",
    "Tunaditor": "ツナディター",
    "Scroll X: ": "スクロール X: ",
    "Scroll Y: ": "スクロール Y: ",
    "Toggle Show/Hide": "見える/見えない",
    "Access Layer L": "レイヤーを入れ L",
    "Edit Cutscene": "動画を編集する",
    "Rename Cutscene": "動画の名を変える",
    "Delete Cutscene": "動画を消す",
    "Are you sure you want to leave?": "本当に出していいですか？",
    "Back to Editing": "いいえ、もどれ",
    "Save and Quit": "はい、保存して出る",
    "Quit without Saving": "はい、保存しなくて出る",

    "New Player": "新たなプレーヤー",
    "New Layer": "新たなレイヤー",
    "New Entity Type": "新たなNPCタイプ",
    "New Collectible Type": "新たなアイテムタイプ",
    "New Background Layer": "新たな背景レイヤー",
    "New Zone": "新たなゾーン",
    "New Text": "新たなテキスト",
    "Select Instance": "物体を選択する",
    "Select Instance Type": "物体タイプを選択する",
    "Select Background Layer": "背景レイヤーを選択する",
    "ESC to Cancel": "ESC で戻る",
    "Create Object": "物体を選べる",

    "Toggle Behavior": "動作を切り替える",
    "Decrease": "減らす",
    "Increase": "増える",
    "Decrease Decimal": "小数点を減らす",
    "Increase Decimal": "小数点を増える",
    "Next Page": "次のページ",
    "Use Stat": "ステータスを使う",
    "Finish Entity Type": "エンティティタイプを完成する",

    "Game Statistics": "ゲーム統計",
    "Statistics and İnventory": "統計とインベントリー",
    "Set Game Style": "ゲームスタイル",
    "Ports and Devices": "ポートとデバイス",
    "Customize Controls for Inputs and Events": "入力とイベントをカスタマイズする",
    "Application Settings": "アプリケーション設定",
    "Control the Resolution and FPS": "画面解像度とFPS",
    "General Settings": "一般的な設定",
    "Set Up Tile Size": "タイル大きさ",

    "Display Settings": "画面設定",
    "Change Display": "画面大きさ",
    "Change FPS": "ゲームFPS",
    "Use DT: ": "DeltaTime: ",

    "Go Back": "戻れ",
    "Add Room": "ルームを作る",
    "Edit Room": "ルームを編集する",
    "Rename Room": "ルームの名を変える",
    "Delete Room": "ルームを消す",
    "Create Door to This Room": "このルームへ連れてドアーを作る",
    "Edit Room's Menu": "ルームのメニューを編集する",
    "Room Manager": "ルーム管理",
    "Borders": "限界",
    "Right: ": "右: ",
    "Left: ": "左: ",
    "Top: ": "上: ",
    "Bottom: ": "下: ",
    "Total Cutscenes: ": "動画 額: ",
    "Total Actors: ": "NPC 額: ",
    "Total Layers: ": "レイヤー額: ",
    "Track: ": "音楽: ",
    "Move Up": "上へ",
    "Move Down": "下へ",

    "Page": "ページ",
    "Press L (-) and R (+) to Access More Glyphs:": "もっとグリフをアクセスするには L (-) と R (+)を押す：",
    "Press ENTER to Confirm, ESC to Cancel": "ENTERを押して確認、ESCで戻る",
  
    "Room: ": "ルーム: ",
    "Play Track (First)": "始めの音楽をプレーする",
    "Play Track (Loop)": "ループの音楽をプレーする",
    "Browse Tracks (First)": "始めの音楽を探す",
    "Browse Tracks (Loop)": "ループの音楽を探す",
    "Stop Track": "音楽を止める",
    "Browse SFX": "音を探す",
    "Change Border": "限界を変える",
    "Right Border": "右の限界",
    "Left Border": "左の限界",
    "Top Border": "上の限界",
    "Bottom Border": "下の限界",
    "Scrolling Mode: ": "スクロールモード: ",
    "Hide Players in This Room": "このルームでプレーヤーを見えない",
    "Apply Shader": "シェーダを適用する",
    "Shader: ": "シェーダ: ",
    "No Scrolling": "スクロールいない",
    "Default Scrolling": "普通なスクロール",
    "Rounded Scrolling": "切り捨てスクロール",
    "Focus on Center": "中心焦点",
    "Horizontal Mirror": "水平ミラー",
    "Vertical Mirror": "垂直ミラー",
    "Gravity": "重力",
    "Decrease Gravity": "重力を減らす",
    "İncrease Gravity": "重力を増える",
    "Token": "トークン",
    "Mode": "モード",
    "Decrease Uİ Token": "トークンを減らす",
    "İncrease Uİ Token": "トークンを増える",
    "Decrease Uİ Mode": "モードを減らす",
    "İncrease Uİ Mode": "モードを増える",
    "Add to Show": "UIモードを見える",
    "Add to Hide": "UIモードを見えない",
    "Uİ Tokens to Show: ": "見えるUIモード: ",
    "Uİ Tokens to Hide: ": "見えないUIモード: ",
    "Tokens Set to Mode (T, M): ": "モードへスウィッチトークン (トークン, モード): ",
    "Set Mode for Selected Token": "選択されたトークンのモードを設定する",
    "Press L (-) and R (+) to Access More Settings:": "もっと設定をアクセスするには L (-) と R (+)を押す：",
    "Add Track": "音楽を追加",
    "Remove Track": "音楽を削除",
    "Gameplay Mode: ": "ゲームプレイモード: ",
    "Platformer": "プラットフォーム",
    "Top-Down": "トップダウン",

    "Layer Options": "レイヤー設定",
    "Collectibles": "アイテム",
    "Actors": "NPC",
    "Toggle Solidity": "固体 オン/オフ",
    "Toggle Slipperiness": "つるつる オン/オフ",
    "Toggle Flatness": "フラット オン/オフ",
    "Set Label": "ラベル",
    "Closer": "近い",
    "Further": "遠い",
    "Dimmer": "暗い",
    "Brighter": "明るい",
    "Delete Layer": "レイヤーを消す",
    "Display Resolution and Tile Size do not Match Up!": "画面の大きさとタイルの大きさでは矛盾がある！",
    
    "Add Sound Effect": "音を加えて",
    "Play Sound Effect": "音をプレイして",
    "Remove Sound Effect": "音を消す",
    "Browse SFXs": "音を探す",
    "Delete Collectible Type Object": "アイテムタイプを消す",
    "Add Background Layer": "背景を加えて",
    "Delete Background": "背景を消す",
    "Repeat X": "Xから繰り返す",
    "Repeat Y": "Yから繰り返す",
    "Toggle X Scroll": "水平ミラー",
    "Toggle Y Scroll": "垂直ミラー",
    "Horizontal Mirroring": "水平ミラー",
    "Vertical Mirroring": "垂直ミラー",
    "Move Front": "前へ",
    "Move Back": "後ろへ",
    "Toggle Foreground": "最前面へ",
    "Set Background to Player Character": "背景をプレーヤーキャラクターにする",
    "Copy Image Path of Background": "背景の画像パスをコピーする",
    "Decrease X Speed": "Xスピードを減らす",
    "İncrease X Speed": "Xスピードを増える",
    "Decrease Y Speed": "Yスピードを減らす",
    "İncrease Y Speed": "Yスピードを増える",
    "Decrease X": "Xを減らす",
    "İncrease X": "Xを増える",
    "Decrease Y": "Yを減らす",
    "İncrease Y": "Yを増える",
    "Decrease X Speed/Destination": "Xスピード/目的地を減らす",
    "İncrease X Speed/Destination": "Xスピード/目的地を増える",
    "Decrease Y Speed/Destination": "Yスピード/目的地を減らす",
    "İncrease Y Speed/Destination": "Yスピード/目的地を増える",









  },
  "NL": {
    "": "",
    "Load Game": "Spel Laden",
    "Save Game State": "Spel Staat Laden",
    "Load Game State": "Spel Staat Opslaan",
    "Restart Game": "Herstart Spel",
    "Eject": "Kaart Uithalen",
    "Switch to Editor": "Naar Editor",
    "Power Off": "Afsluiten",

    "Configure...": "Configuraties",
    "Settings": "Instellingen",
    "Miscellaneous": "Apparaat",
    "Open Terminal": "Console Openen",
    "Toggle Debug Mode": "Debug Mode",
    "Load Additional Packages": "Extra Pakketten Laden",
    "Refresh": "Herlaad",
    "Retry": "Weer Proberen",

    "Profile": "Profiel",
    "Host Server": "Server Hosten",
    "Connect to Server": "Naar Server Verbinden",
    "Performance": "Performance",

    "Input": "Input",
    "Video": "Video",
    "Audio": "Audio",
    "Set Device": "Apparaat Instellen",
    "Set Deadzone": "Deadzone Instellen",
    "Refresh Connections": "Verbindingen Herladen",
    "Rumble: ": "Trilling: ",
    "Render Filter": "Render Filter",
    "Color Swizzle": "Kleur Swizzle",
    "Set Render Mode": "Render Mode Instellen",
    
    "Network Monitor": "Netwerk Monitor",


    "Add Instance": "Instance Toevoegen",
    "Delete Object": "Object Verwijderen",
    "Edit Object": "Object Wijzigen",
    "Manage Rooms": "Beheer Kamers",
    "Add Cutscene": "Cutscene Toevoegen",
    "General Game Settings": "Algemene Spel Instellingen",
    "Playtest": "Playtest",
    "Stop Playtest": "Stop Playtest",
    "Save Game": "Spel Opslaan",
    "Load Game": "Spel Laden",
    "No cutscenes in this room": "Er zijn geen cutscenes",
    "No object selected": "Geen object geselectreerd",
    "Selected Object: ": "Geselecteerde Object",
    "İn Room: ": "İn Kamer: ",
    "Tunaditor": "Tunaditor",
    "Scroll X: ": "Scroll X: ",
    "Scroll Y: ": "Scroll Y: ",
    "Toggle Show/Hide": "Schakel Zichtbaarheid",
    "Access Layer L": "Ga naar Laag L",
    "Edit Cutscene": "Wijzig Cutscene",
    "Rename Cutscene": "Hernoem Cutscene",
    "Delete Cutscene": "Verwijder Cutscene",
    "Are you sure you want to leave?": "Weet je zeker dat je wilt verlaten?",
    "Back to Editing": "Nee, neem me terug",
    "Save and Quit": "Ja, sla op en verlaat",
    "Quit without Saving": "Ja, verlaat zonder op te slaan",

    "New Player": "Nieuwe Speler",
    "New Layer": "Nieuwe Laag",
    "New Entity Type": "Nieuwe Entity Type",
    "New Collectible Type": "Nieuwe Collectible Type",
    "New Background Layer": "Nieuwe Achtergrond Laag",
    "New Zone": "Nieuwe Zone",
    "New Text": "Nieuwe Tekst",
    "Select Instance": "Selecteer Instance",
    "Select Instance Type": "Selecteer Instance Type",
    "Select Background Layer": "Selecteer Achtergrond Laag",
    "ESC to Cancel": "ESC om terug te gaan",
    "Create Object": "Nieuwe Object",
    
    "Toggle Behavior": "Kies Gedrag Uit",
    "Next Page": "Volgende Pagina",
    "Decrease": "Verlaag",
    "Increase": "Verhoog",
    "Decrease Decimal": "Verlaag Decimaal",
    "Increase Decimal": "Verhoog Decimaal",
    "Use Stat": "Gebruik Statistiek",
    "Finish Entity Type": "Compleet Entity Type",

    "Game Statistics": "Spel Statistieken",
    "Statistics and İnventory": "Statistieken en Inventaris",
    "Set Game Style": "Spel Stijl İnstellen",
    "Ports and Devices": "Porten en Apparaten",
    "Customize Controls for Inputs and Events": "Verander Controls voor Input en Event",
    "Application Settings": "Applicatie İnstellingen",
    "Control the Resolution and FPS": "Scherm Grootte en FPS",
    "General Settings": "Algemene İnstellingen",
    "Set Up Tile Size": "Stel Tegel Grootte İn",

    "Display Settings": "Scherm İnstellingen",
    "Change Display": "Scherm Grootte",
    "Change FPS": "Scherm FPS",
    "Use DT: ": "Gebruik DT: ",

    "Go Back": "Ga Terug",
    "Add Room": "Nieuwe Kamer",
    "Edit Room": "Kamer Wijzigen",
    "Rename Room": "Kamer Hernoemen",
    "Delete Room": "Kamer Verwijderen",
    "Create Door to This Room": "Nieuwe Deur naar dit Kamer",
    "Edit Room's Menu": "Stel Kamer Menu İn",
    "Room Manager": "Kamers Beheren",
    "Borders": "Grenzen",
    "Right: ": "Rechts: ",
    "Left: ": "Links: ",
    "Top: ": "Top: ",
    "Bottom: ": "Bodem: ",
    "Total Cutscenes: ": "Totaal Cutscene: ",
    "Total Actors: ": "Totaal Entity's: ",
    "Total Layers: ": "Totaal Lagen: ",
    "Track: ": "Liedje: ",
    "Move Up": "Neem Omhoog",
    "Move Down": "Neem Omlaag",

    "Page": "Pagina",
    "Press L (-) and R (+) to Access More Glyphs:": "Om meer glyphs te zien, druk op L (-) en R (+):",
    "Press ENTER to Confirm, ESC to Cancel": "Bevestig met ENTER, Annuleer met ESC",
    
    "Room: ": "Kamer: ",
    "Play Track (First)": "Speel Eerste Liedje Af",
    "Play Track (Loop)": "Speel Loopend Liedje Af",
    "Browse Tracks (First)": "Zoek Eerste Liedje",
    "Browse Tracks (Loop)": "Zoek Loopend Liedje",
    "Stop Track": "Stop Liedje",
    "Browse SFX": "Zoek Geluidseffecten",
    "Change Border": "Verander Grens",
    "Right Border": "Rechter Grens",
    "Left Border": "Linker Grens",
    "Top Border": "Top Grens",
    "Bottom Border": "Bodem Grens",
    "Scrolling Mode: ": "Scrolling Mode: ",
    "Hide Players in This Room": "Verberg Spelers in deze Kamer",
    "Apply Shader": "Voeg Shader Toe",
    "Shader: ": "Shader: ",
    "No Scrolling": "Geen Scrolling",
    "Default Scrolling": "Normale Scroll",
    "Rounded Scrolling": "Afgeronde Scroll",
    "Focus on Center": "Centrale Focus",
    "Horizontal Mirror": "Horizontale Spiegeling",
    "Vertical Mirror": "Verticale Spiegeling",
    "Gravity": "Zwaartekracht",
    "Decrease Gravity": "Verlaag Zwaartekracht",
    "İncrease Gravity": "Verhoog Zwaartekracht",
    "Token": "Token",
    "Mode": "Mode",
    "Decrease Uİ Token": "Hoger Token",
    "İncrease Uİ Token": "Lager Token",
    "Decrease Uİ Mode": "Lager Mode",
    "İncrease Uİ Mode": "Hoger Mode",
    "Add to Show": "Maak Uİ Mode Zichtbaar",
    "Add to Hide": "Maak Uİ Mode Onzichtbaar",
    "Uİ Tokens to Show: ": "Zichtbare Uİ Tokens: ",
    "Uİ Tokens to Hide: ": "Onzichtbare Uİ Tokens: ",
    "Tokens Set to Mode (T, M): ": "Tokens naar Mode wisselen (T, M): ",
    "Set Mode for Selected Token": "Zet Mode voor de Geselecteerde Token",
    "Press L (-) and R (+) to Access More Settings:": "Om meer instellingen te zien, druk op L (-) en R (+):",
    "Add Track": "Voeg Liedje Toe",
    "Remove Track": "Verwijder Liedje",
    "Gameplay Mode: ": "Gameplay Modus: ",
    "Platformer": "Platformer",
    "Top-Down": "Top-Down",

    "Layer Options": "Laag Opties",
    "Collectibles": "Collectibles",
    "Actors": "Entities",
    "Toggle Solidity": "Stevigheid Aan/Uit",
    "Toggle Slipperiness": "Gladheid Aan/Uit",
    "Toggle Flatness": "Platheid Aan/Uit",
    "Set Label": "Plak een Label Aan",
    "Closer": "Dichterbij",
    "Further": "Verderweg",
    "Dimmer": "Donkerder",
    "Brighter": "Helder",
    "Delete Layer": "Verwijder Laag",
    "Display Resolution and Tile Size do not Match Up!": "Scherm Grootte en Tegel Grootte Stellen Elkaar Tegen!",
    
    "Add Sound Effect": "Voeg Geluid Toe",
    "Play Sound Effect": "Speel Geluid Af",
    "Remove Sound Effect": "Verwijder Geluid",
    "Browse SFXs": "Browse Geluiden",
    "Delete Collectible Type Object": "Verwijder Collectible Type",
    "Add Background Layer": "Voeg Achtergrond Laag Toe",
    "Delete Background": "Verwijder Achtergrond",
    "Repeat X": "Herhaal vanaf X",
    "Repeat Y": "Herhaal vanaf Y",
    "Toggle X Scroll": "X Scrolling",
    "Toggle Y Scroll": "Y Scrolling",
    "Horizontal Mirroring": "Horizontale Spiegeling",
    "Vertical Mirroring": "Verticale Spiegeling",
    "Move Front": "Breng naar Voor",
    "Move Back": "Breng naar Achter",
    "Toggle Foreground": "Voorgrond Aan/Uit",
    "Set Background to Player Character": "Stel Achtergrond in als Player Karakter",
    "Copy Image Path of Background": "Kopiëer Achterground Afbeelding Pad",
    "Decrease X Speed": "Verlaag X Snelheid",
    "İncrease X Speed": "Verhoog X Snelheid",
    "Decrease Y Speed": "Verlaag Y Snelheid",
    "İncrease Y Speed": "Verhoog Y Snelheid",
    "Decrease X": "Verlaag X",
    "İncrease X": "Verhoog X",
    "Decrease Y": "Verlaag Y",
    "İncrease Y": "Verhoog X",
    "Decrease X Speed/Destination": "Verlaag X Snelheid/Bestemming",
    "İncrease X Speed/Destination": "Verhoog X Snelheid/Bestemming",
    "Decrease Y Speed/Destination": "Verlaag Y Snelheid/Bestemming",
    "İncrease Y Speed/Destination": "Verhoog Y Snelheid/Bestemming",
  },
}

for string in l["AR"]: l["AR"][string] = l["AR"][string] + "    "